### ISSUE TITLE
Link para o GitHub

### ISSUE THREAD

**Issue by luisangelorjr** [ThiagoWaishaupt/ThiagoWaishaupt.github.io#1]
Mano, coloca um link para o GitHub no rodapé

**Comment by ThiagoWaishaupt** [comment]
TALKEI TALKEI TALKEI.

Coloquei o link do Page naquele arquivo README só.

Amanha de manha coloco o do GitHub no rodapé


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Luís Ângelo Rodrigues Jr. <notifications@github.com>
Enviado: Thursday, August 22, 2019 12:00:46 AM
Para: ThiagoWaishaupt/ThiagoWaishaupt.github.io <ThiagoWaishaupt.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ThiagoWaishaupt/ThiagoWaishaupt.github.io] Link para o GitHub (#1)


Mano, coloca um link para o GitHub no rodapé
