### ISSUE TITLE
Link para o FreeCodeCamp

### ISSUE THREAD

**Issue by luisangelorjr** [ThiagoWaishaupt/ThiagoWaishaupt.github.io#3]
Mano, colocar um link para o FreeCodeCamp

**Comment by ThiagoWaishaupt** [comment]
Caralho calma ae. Vou procurar aquelas bolinhas com as redes sociais que vc tem no seu e colocar

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Luís Ângelo Rodrigues Jr. <notifications@github.com>
Enviado: Thursday, August 22, 2019 12:01:54 AM
Para: ThiagoWaishaupt/ThiagoWaishaupt.github.io <ThiagoWaishaupt.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ThiagoWaishaupt/ThiagoWaishaupt.github.io] Link para o FreeCodeCamp (#3)


Mano, colocar um link para o FreeCodeCamp
