### ISSUE TITLE
Link para o melhor DevFullSquack de que se tem notícias

### ISSUE THREAD

**Issue by luisangelorjr** [ThiagoWaishaupt/ThiagoWaishaupt.github.io#4]
Mano, coloca um link de agradecimento para o melhor pior dev fullSquack que vc conhece e que te apresentou esse mundo novo e legal da internet de meo deos

**Comment by ThiagoWaishaupt** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKK pode pa

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Luís Ângelo Rodrigues Jr. <notifications@github.com>
Enviado: Thursday, August 22, 2019 12:03:07 AM
Para: ThiagoWaishaupt/ThiagoWaishaupt.github.io <ThiagoWaishaupt.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [ThiagoWaishaupt/ThiagoWaishaupt.github.io] Link para o melhor DevFullSquack de que se tem notícias (#4)


Mano, coloca um link de agradecimento para o melhor pior dev fullSquack que vc conhece e que te apresentou esse mundo novo e legal da internet de meo deos
